name: FunctionalTests

on: [push, pull_request]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-22.04]
        php-version: ['7.4', '8.0', '8.1']
        db: ['mariadb', 'postgres']

    name: Testing PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}

    steps:
      - uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json,intl,mbstring

      - name: Checkout repository
        uses: actions/checkout@v3

      - run: Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s composerInstall
      - run: Build/Scripts/runTests.sh -p ${{ matrix.php-version }} -s functional -d ${{matrix.db}}
